build_script:
- cmd: >-
   rem Path for MinGW is first, then path for make
   rem
    set PATH=c:\msys64\MinGW32\bin;c:\msys64\usr\bin;%PATH% &
    make CC=gcc

test_script:
- cmd: >-
    file_tree_walk.exe Dir1                                      &
    c:\msys64\usr\bin\echo -e '\e[1;32mRegenerating myself\e[0m' &
    gen-make.exe -G windows                                      &
    make CC=gcc -f Makefile.windows                              &
    foo.exe



