install:
  #
  # Prepend the PATH for 'make' + 'sh' etc.
  # And set compiler environment for MSVC/clang-cl:
  #
  - cmd: set PATH=c:\msys64\usr\bin;%PATH%
  - cmd: call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
  - cmd: make CC=cl

test_script:
  - cmd: make CC=cl test



