build_script:
- cmd: >-
   rem Path for MinGW is first, then path for make
   set PATH=c:\msys64\MinGW32\bin;c:\msys64\usr\bin;%PATH% &
   make CPU=x64 CC=gcc

test_script:
- cmd: >-
    file_tree_walk.exe Dir1                                      &
    c:\msys64\usr\bin\echo -e '\e[1;32mRegenerating myself\e[0m' &
    set CPU=x64                                                  &
    gen-make.exe -G windows                                      &
    make CPU=x64 CC=gcc -f Makefile.windows                      &
    foo.exe



