#
# GNU makefile for gen-make.
# Needs MinGW, MinGW64, cl or clang-cl.
#
OBJ_DIR = objects

#
# This assumes you have CygWin/Msys's 'echo' with colour support."
#
green_msg = @echo -e '\e[1;32m$(strip $(1))\e[0m'

define Usage

  Usage: $(MAKE) CC=[gcc | cl, clang-cl]
endef

ifeq ($(CC),clang-cl)
  export CL=
  RCFLAGS = -nologo -D__clang__

else ifeq ($(CC),cl)
  RCFLAGS = -nologo -D_MSC_VER

else ifeq ($(CC),gcc)
  CC       = gcc
  CFLAGS   = -m32 -Wall -O2
  RCFLAGS = -O COFF --target=pe-i386
  link_EXE = $(CC) -m32 -s -o $(1) $(2)
  O        = o

else
  $(error $(Usage))
endif

ifneq ($(CC),gcc)
  CFLAGS = -nologo -MD -W2 -O2 -D_CRT_SECURE_NO_WARNINGS \
           -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE \
           -D_CRT_OBSOLETE_NO_WARNINGS

  link_EXE = link -nologo -debug -incremental:no -out:$(strip $(1)) $(2)
  O        = obj
endif

#
# A "foo.exe" program built with a Makefile generated by "gen-make",
# in this directory checks for this. Since 'gen-make.c' here has a
# valid 'main()' do not allow it to generate any more makefiles.
#
CFLAGS += -DIN_THE_REAL_MAKEFILE

SOURCES = gen-make.c        \
          file_tree_walk.c  \
          smartlist.c       \
          template-mingw.c  \
          template-cygwin.c \
          template-msvc.c   \
          template-watcom.c \
          template-windows.c

ifneq ($(CC),gcc)
  VPATH    = msvc
  SOURCES += msvc/getopt_long.c
  CFLAGS  += -I.
endif

OBJECTS = $(addprefix $(OBJ_DIR)/, \
            $(notdir $(SOURCES:.c=.$(O))) )

all: $(OBJ_DIR) gen-make.exe file_tree_walk.exe

$(OBJ_DIR):
	- mkdir $@

gen-make.exe: $(OBJECTS) $(OBJ_DIR)/gen-make.res
	$(call green_msg, Linking $@)
	$(call link_EXE, $@, $^)
	@echo

file_tree_walk.exe: file_tree_walk.c
	$(call green_msg, Compiling and linking $@)
	$(CC) -c -DTEST $(CFLAGS) $<
	$(call link_EXE, $@, file_tree_walk.$(O))
	rm -f file_tree_walk.$(O)
	$(call green_msg, Test me using "file_tree_walk.exe test-dir\\")
	@echo

test: gen-make.exe
	cd hello_world                                ; \
	../gen-make -nG windows > Makefile.Windows    ; \
	$(MAKE) -f Makefile.Windows CC=gcc depend all ; \
	foo.exe

$(OBJ_DIR)/%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
	@echo

$(OBJ_DIR)/%.obj: %.c
	$(CC) $(CFLAGS) -c -Fo./$@ $<
	@echo

ifeq ($(CC),gcc)
$(OBJ_DIR)/gen-make.res: gen-make.rc
	windres $(RCFLAGS) -o $@ $<
	@echo
else
$(OBJ_DIR)/gen-make.res: gen-make.rc
	rc $(RCFLAGS) -fo$@ $<
	@echo
endif

clean:
	rm -f $(OBJ_DIR)/* gen-make.exe gen-make.res file_tree_walk.exe
	rm -f gen-make.pdb file_tree_walk.pdb
	rmdir $(OBJ_DIR)

$(OBJ_DIR)/gen-make.$(O):         gen-make.c gen-make.h smartlist.h
$(OBJ_DIR)/gen-make.res:          gen-make.rc gen-make.h
$(OBJ_DIR)/file_tree_walk.$(O):   file_tree_walk.c
$(OBJ_DIR)/smartlist.$(O):        smartlist.c smartlist.h
$(OBJ_DIR)/template-mingw.$(O):   template-mingw.c gen-make.h
$(OBJ_DIR)/template-cygwin.$(O):  template-cygwin.c gen-make.h
$(OBJ_DIR)/template-msvc.$(O):    template-msvc.c gen-make.h
$(OBJ_DIR)/template-watcom.$(O):  template-watcom.c gen-make.h
$(OBJ_DIR)/template-windows.$(O): template-windows.c gen-make.h
$(OBJ_DIR)/getopt_long.$(O):      msvc/getopt_long.c msvc/getopt_long.h

